const MARK_AS_READ = 'MARK_AS_READ';
const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
const NotificationTypeFilters = {
  DEFAULT: 'DEFAULT',
  URGENT: 'URGENT',
};

export { MARK_AS_READ, SET_TYPE_FILTER, FETCH_NOTIFICATION_SUCCESS, NotificationTypeFilters };